# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - 
    trigger: ":espanso"
    replace: "Hi there!"
  - 
    trigger: "yee"
    replace: "🦎"
  - 
    trigger: ";x;"
    replace: "❌"
  - 
    trigger: ";o;"
    replace: "⭕"
  - 
    trigger: ";check;"
    replace: "☑️"
  - 
    trigger: ";thumb;"
    replace: "👍"
  - 
    trigger: "newtri"
    replace: "\";$|$;\",\"{{clipboard}}\""
    vars:
      - name: "clipboard"
        type: "clipboard"
  -
    trigger: ";fever;"
    replace: "🌡️ 發燒 "
  -
    trigger: ";treat;"
    replace: "💊 治療 "
  -
    trigger: ";flu;"
    replace: "🤒 感染"
  -
    trigger: ";pe;"
    replace: "🏋️ 理學檢查 "
  -
    trigger: ";lab;"
    replace: "🩸 實驗室檢查 "
  -
    trigger: ";se;"
    replace: "👻 副作用"
  -
    trigger: ";nb;"
    replace: "🚨 注意"
  -
    trigger: ";iv;"
    replace: "💉 用藥"
  -
    trigger: ";bac;"
    replace: "🦠"
  -
    trigger: ";pulm;"
    replace: "🫁"
  -
    trigger: ";neuro;"
    replace: "🧠"
  - 
    trigger: ";n;"
    replace: "<br>"

  - trigger: "ccard"
    replace: "#🧠 *Q&A* $|$ →→ "
  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
