matches:
  - trigger: ":espanso"
    replace: Hi there!
  - trigger: yee
    replace: 🦎
  - trigger: ":x:"
    replace: ❌
  - trigger: ;o;
    replace: ⭕
  - trigger: ;check;
    replace: ☑️
  - trigger: ;thumb;
    replace: 👍
  - trigger: newtri
    replace: "\";$|$;\",\"{{clipboard}}\""
    vars:
      - name: clipboard
        type: clipboard
  - trigger: ;fever;
    replace: "🌡️ 發燒 "
  - trigger: ;mx;
    replace: "💊治療 "
  - trigger: ;pathophy;
    replace: 🔄致病機轉
  - trigger: ;sum;
    replace: 📖結論
  - trigger: ;kissalot;
    replace: 🥰😍🤩😘😗😚
  - trigger: ;;
    replace: ""
  - trigger: ;;
    replace: ""
  - trigger: ;flu;
    replace: 🤒感染
  - trigger: ;pe;
    replace: "🏋️ 理學檢查 "
  - trigger: ;lab;
    replace: "🧪Lab 檢查 "
  - trigger: ;se;
    replace: 👻副作用
  - trigger: ;nb;
    replace: 🚨
  - trigger: ;rx;
    replace: 💉藥
  - trigger: ;bac;
    replace: 🦠
  - trigger: ;pulm;
    replace: 🫁
  - trigger: ;neuro;
    replace: 🧠
  - trigger: ;+;
    replace: ➕
  - trigger: ;skull;
    replace: 💀
  - trigger: ;rad;
    replace: ☢️
  - trigger: ;!!;
    replace: ‼️
  - trigger: ;approach;
    replace: 🔰
  - trigger: ;warn;
    replace: ⚠️
  - trigger: ;hazard;
    replace: ☣️
  - trigger: ;cvrisk;
    replace: "🫀 心血管風險 "
  - trigger: ;gg;
    replace: 😵
  - trigger: ;hema;
    replace: 🩸
  - trigger: ;img;
    replace: "🌠 影像檢查  "
  - trigger: ;bolt;
    replace: ⚡
  - trigger: ;n;
    replace: "<br>"
  - trigger: ;ddx;
    replace: 🔍鑑別診斷🔎
  - trigger: ;flow;
    replace: |
      ```mermaid
      `%%{init: {'securityLevel': 'loose','theme':'base','themeVariables': { 'primaryColor': '#fff'}}}%%
      graph TD;
      A[$|$];
      B[left];
      C[right];
      A-->B;A-->C;
      ```
  - trigger: ccard
    replace: "#🧠 *Q&A* $|$ →→ "
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y/%m/%d"
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: echo Hello from your shell
